### ISSUE TITLE
click RichEditText (has words)  android phone  crash

### ISSUE THREAD

**Issue by liuxiangteng** [CarGuo/RickText#26]

**Comment by CarGuo** [comment]
how to reappear in demo

**Comment by liuxiangteng** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                      at com.shuyu.textutillib.RichEditText.resolveEditTextClick(RichEditText.java:256)
                      at com.shuyu.textutillib.RichEditText.access$500(RichEditText.java:38)
                      at com.shuyu.textutillib.RichEditText$2.onClick(RichEditText.java:349)
                      at android.view.View.performClick(View.java:6304)
                      at android.view.View$PerformClick.run(View.java:24803)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6600)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by CarGuo** [comment]
As shown in the log，you can't make  nameList null，like demo：
```
 .setListUser(nameList)
.setListTopic(topicModels)
```
if you don't need them , set `new ArrayList<>()` for it
